name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Resume.tex
