name: Build & Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Resume.tex
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Resume
          path: Resume.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Resume.pdf
          body_path: CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
